import { readdirSync, writeFileSync, statSync, existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

export function getAllFiles(dir, base = "") {
  if (!existsSync(dir)) return [];
  let results = [];
  const list = readdirSync(dir);
  for (const file of list) {
    if (file.startsWith(".") || file === "sw.js" || file === "generate-sw.mjs" || file.endsWith(".md")) continue;
    const fullPath = join(dir, file);
    const relPath = base ? `${base}/${file}` : file;
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      if (file === "goat-card-images") continue;
      results = results.concat(getAllFiles(fullPath, relPath));
    } else {
      results.push(`./${relPath.replace(/\\/g, "/")}`);
    }
  }
  return results;
}

export function generateServiceWorker(distDir = "dist", rootDir = ".") {
  const rawFiles = getAllFiles(distDir);
  const filesToPrecache = Array.from(new Set([
    "./",
    "./index.html",
    "index.html",
    ...rawFiles
  ]));

  const cacheVersion = `goat-ipad-offline-v${Date.now()}`;

  const swCode = `// Autogenerated offline Service Worker for GOAT Local Lab
const CACHE_NAME = "${cacheVersion}";

const PRECACHE_ASSETS = ${JSON.stringify(filesToPrecache, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(async (cache) => {
      console.log("[PWA SW] Pre-caching all app assets for 100% offline play...");
      await Promise.allSettled(
        PRECACHE_ASSETS.map(async (url) => {
          try {
            const res = await fetch(url);
            if (res.ok || res.type === "opaque") {
              await cache.put(url, res);
            }
          } catch (e) {
            console.warn("[PWA SW] Non-fatal precache item skip:", url);
          }
        })
      );
      console.log("[PWA SW] Pre-cache complete! App is ready for offline play.");
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      );
    }).then(() => {
      console.log("[PWA SW] Claiming clients for offline control");
      return self.clients.claim();
    })
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  // 1. Navigation requests (opening the app from Home Screen / Safari offline)
  if (request.mode === "navigate" || request.destination === "document") {
    event.respondWith(
      (async () => {
        try {
          const networkResponse = await fetch(request);
          if (networkResponse && networkResponse.status === 200) {
            const cache = await caches.open(CACHE_NAME);
            cache.put(request, networkResponse.clone());
            return networkResponse;
          }
        } catch (e) {
          // Device is offline: retrieve index.html from cache
        }
        const cache = await caches.open(CACHE_NAME);
        const cached =
          (await cache.match(request)) ||
          (await cache.match("./index.html")) ||
          (await cache.match("index.html")) ||
          (await cache.match("./")) ||
          (await cache.match("/"));
        if (cached) return cached;
        return new Response("<!doctype html><html><body><h1>GOAT Lab Offline</h1></body></html>", {
          headers: { "Content-Type": "text/html" }
        });
      })()
    );
    return;
  }

  // 2. Static assets (JS, CSS, wasm, images, sprites, webmanifest)
  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      const cachedResponse = await cache.match(request, { ignoreSearch: true });
      if (cachedResponse) return cachedResponse;

      // Try matching by relative URL or pathname
      try {
        const url = new URL(request.url);
        const pathMatch = await cache.match("." + url.pathname, { ignoreSearch: true }) ||
                          await cache.match(url.pathname, { ignoreSearch: true });
        if (pathMatch) return pathMatch;
      } catch (_) {}

      try {
        const networkResponse = await fetch(request);
        if (networkResponse && (networkResponse.status === 200 || networkResponse.type === "opaque")) {
          const clone = networkResponse.clone();
          await cache.put(request, clone);
        }
        return networkResponse;
      } catch (err) {
        // Fallback search in cache by filename
        try {
          const url = new URL(request.url);
          const filename = url.pathname.split("/").pop();
          if (filename) {
            const match = await cache.match(filename, { ignoreSearch: true }) ||
                          await cache.match("./sprites/" + filename, { ignoreSearch: true }) ||
                          await cache.match("./assets/" + filename, { ignoreSearch: true });
            if (match) return match;
          }
        } catch (_) {}

        // For images, return a dummy 1x1 transparent PNG fallback instead of throwing
        if (request.destination === "image") {
          return new Response(
            new Uint8Array([
              0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d,
              0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
              0x08, 0x06, 0x00, 0x00, 0x00, 0x1f, 0x15, 0xc4, 0x89, 0x00, 0x00, 0x00,
              0x0a, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9c, 0x63, 0x00, 0x01, 0x00, 0x00,
              0x05, 0x00, 0x01, 0x0d, 0x0a, 0x2d, 0xb4, 0x00, 0x00, 0x00, 0x00, 0x49,
              0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82
            ]),
            { headers: { "Content-Type": "image/png" } }
          );
        }
        return new Response("", { status: 404, statusText: "Offline Resource Unavailable" });
      }
    })()
  );
});
`;

  try {
    writeFileSync(join(distDir, "sw.js"), swCode, "utf8");
    if (rootDir && existsSync(rootDir)) {
      writeFileSync(join(rootDir, "sw.js"), swCode, "utf8");
    }
    console.log(`[generate-sw] Generated offline Service Worker with ${filesToPrecache.length} pre-cached assets!`);
  } catch (err) {
    console.warn("[generate-sw] Warning generating sw.js:", err);
  }
}

// If run directly via `node generate-sw.mjs`
if (process.argv[1] && (process.argv[1].endsWith("generate-sw.mjs") || process.argv[1].endsWith("generate-sw.js"))) {
  generateServiceWorker("dist", ".");
}

