import { readdirSync, writeFileSync, statSync, readFileSync } from "node:fs";
import { join } from "node:path";

function getAllFiles(dir, base = "") {
  let results = [];
  const list = readdirSync(dir);
  for (const file of list) {
    if (file.startsWith(".") || file === "sw.js" || file === "generate-sw.mjs") continue;
    const fullPath = join(dir, file);
    const relPath = base ? `${base}/${file}` : file;
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      // For goat-card-images, we don't need to precache all 1700 images at install time (which would take 50MB upfront),
      // we cache them on-demand when fetched, but we DO precache all core assets and sprites!
      if (file === "goat-card-images") continue;
      results = results.concat(getAllFiles(fullPath, relPath));
    } else {
      results.push(`./${relPath}`);
    }
  }
  return results;
}

const distDir = "dist";
const filesToPrecache = [
  "./",
  "./index.html",
  ...getAllFiles(distDir)
];

const cacheVersion = `goat-ipad-offline-v${Date.now()}`;

const swCode = `// Autogenerated offline Service Worker for GOAT Local Lab
const CACHE_NAME = "${cacheVersion}";

const PRECACHE_ASSETS = ${JSON.stringify(filesToPrecache, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      console.log("[PWA SW] Pre-caching all core app assets for offline play...");
      return cache.addAll(PRECACHE_ASSETS).catch((err) => {
        console.warn("[PWA SW] Pre-cache warning:", err);
      });
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      );
    }).then(() => {
      console.log("[PWA SW] Activated and claimed clients for offline mode");
      return self.clients.claim();
    })
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  event.respondWith(
    caches.match(request).then((cachedResponse) => {
      if (cachedResponse) {
        // Return instantly from local cache
        return cachedResponse;
      }

      // If not in cache, fetch from network and store in cache dynamically
      return fetch(request).then((networkResponse) => {
        if (networkResponse && (networkResponse.status === 200 || networkResponse.type === "opaque")) {
          const clone = networkResponse.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, clone));
        }
        return networkResponse;
      }).catch(async (err) => {
        // When completely offline, fallback navigation requests to index.html
        if (request.mode === "navigate" || request.headers.get("accept")?.includes("text/html")) {
          const fallback = await caches.match("./index.html") || await caches.match("./");
          if (fallback) return fallback;
        }
        throw err;
      });
    })
  );
});
`;

writeFileSync("dist/sw.js", swCode, "utf8");
writeFileSync("sw.js", swCode, "utf8");
console.log(`[generate-sw] Generated offline Service Worker with ${filesToPrecache.length} pre-cached assets!`);
