// Autogenerated offline Service Worker for GOAT Local Lab
const CACHE_NAME = "goat-ipad-offline-v1787319088545";

const PRECACHE_ASSETS = [
  "./",
  "./index.html",
  "index.html",
  "./assets/card-audit-BPv-V_ck.js",
  "./assets/card-audit-BwB4S8Pl.js",
  "./assets/card-audit-C5AcRkLb.js",
  "./assets/card-audit-Dlck7-jZ.js",
  "./assets/card-audit-DqDpv7Zk.js",
  "./assets/card-audit-DrJa8LWN.js",
  "./assets/card-audit-PdwC0nJj.js",
  "./assets/card-audit-PZRdqF-l.js",
  "./assets/card-audit-scenario-BcIFyWcL.js",
  "./assets/card-audit-scenario-CfZVxRsm.js",
  "./assets/card-audit-scenario-CQAH-MNu.js",
  "./assets/card-audit-scenario-D83ybL5u.js",
  "./assets/card-audit-scenario-DdsDoxtd.js",
  "./assets/card-audit-scenario-DQ955j4i.js",
  "./assets/card-audit-scenario-hIYlyoqf.js",
  "./assets/card-audit-scenario-rdFRmqE-.js",
  "./assets/card-audit-scenario-_XwG0DB-.js",
  "./assets/card-audit-VIZ1e9wY.js",
  "./assets/card-viewer-Bsi3tL_G.js",
  "./assets/card-viewer-CJiDIhN8.js",
  "./assets/card-viewer-CtCrg2jr.js",
  "./assets/card-viewer-CTnO7JM_.js",
  "./assets/card-viewer-DDMzFe4M.js",
  "./assets/card-viewer-DL6v8F_V.js",
  "./assets/card-viewer-DsIWsXls.js",
  "./assets/card-viewer-lm1DNF8x.js",
  "./assets/card-viewer-qkL70Alh.js",
  "./assets/chunk-6GYI7QPM-C3jnHFg4.js",
  "./assets/main-9pDEoJzW.js",
  "./assets/main-B-a5f7wT.css",
  "./assets/main-B99tQUrU.js",
  "./assets/main-CE9cyzD5.css",
  "./assets/main-CRGEuPfz.js",
  "./assets/main-D-kmEfPu.js",
  "./assets/main-DBCt-8zE.css",
  "./assets/main-DBRyzdDP.js",
  "./assets/main-DhXrah9M.js",
  "./assets/main-DLOJtFVQ.js",
  "./assets/main-DVvJhx16.css",
  "./assets/main-MHQF7agf.css",
  "./assets/main-pQ0r2lA6.css",
  "./assets/main-qd1UTHah.css",
  "./assets/main-sf56VIdZ.js",
  "./assets/main-ShpJL-oH.css",
  "./assets/main-ZKSYbc7z.js",
  "./assets/manifest-CblUBTob.webmanifest",
  "./assets/ocgcore-script-sources-5UZnbyz9.js",
  "./assets/ocgcore-script-sources-B0j2EM3l.js",
  "./assets/ocgcore-script-sources-B0ucdHDb.js",
  "./assets/ocgcore-script-sources-BAAc2PVM.js",
  "./assets/ocgcore-script-sources-Br7YOiti.js",
  "./assets/ocgcore-script-sources-BYdW0Qsp.js",
  "./assets/ocgcore-script-sources-De91WyNc.js",
  "./assets/ocgcore-script-sources-Kmnd1SoR.js",
  "./assets/ocgcore-script-sources-smB-WRIK.js",
  "./assets/ocgcore.jspi-ROQIC75H-bfkp7QYU.js",
  "./assets/ocgcore.jspi-ROQIC75H-BhNOd6-B.js",
  "./assets/ocgcore.jspi-ROQIC75H-BK1gGWFL.js",
  "./assets/ocgcore.jspi-ROQIC75H-BuYlPy1j.js",
  "./assets/ocgcore.jspi-ROQIC75H-ClnJTuFU.js",
  "./assets/ocgcore.jspi-ROQIC75H-DDLt2mVj.js",
  "./assets/ocgcore.jspi-ROQIC75H-DHIy_LMz.js",
  "./assets/ocgcore.jspi-ROQIC75H-LTgIoT60.js",
  "./assets/ocgcore.jspi-ROQIC75H-qiULrpqX.js",
  "./assets/ocgcore.jspi-W7UMOWZG-Bf3M6XwC.js",
  "./assets/ocgcore.jspi-W7UMOWZG-C2-nXUR0.js",
  "./assets/ocgcore.jspi-W7UMOWZG-C8RbYzQL.js",
  "./assets/ocgcore.jspi-W7UMOWZG-DsZu73YU.js",
  "./assets/ocgcore.jspi-W7UMOWZG-Dx3bzHqz.js",
  "./assets/ocgcore.jspi-W7UMOWZG-HCaxYrvf.js",
  "./assets/ocgcore.jspi-W7UMOWZG-MKcrJdBE.js",
  "./assets/ocgcore.jspi-W7UMOWZG-wZcDIyu3.js",
  "./assets/ocgcore.jspi-W7UMOWZG-zsVwSV01.js",
  "./assets/ocgcore.sync-MMMSWPBB-7moS_zPf.js",
  "./assets/ocgcore.sync-MMMSWPBB-Bh3s_9Qt.js",
  "./assets/ocgcore.sync-MMMSWPBB-BQ7XHsNn.js",
  "./assets/ocgcore.sync-MMMSWPBB-CzYxnRZb.js",
  "./assets/ocgcore.sync-MMMSWPBB-fKZIPgy3.js",
  "./assets/ocgcore.sync-MMMSWPBB-kyD4Dzqu.js",
  "./assets/ocgcore.sync-MMMSWPBB-M66WzlwC.js",
  "./assets/ocgcore.sync-MMMSWPBB-mOyGj0WP.js",
  "./assets/ocgcore.sync-MMMSWPBB-wDwcvmrm.js",
  "./assets/ocgcore.sync-ORIXRHXI-B8Ag-lE1.js",
  "./assets/ocgcore.sync-ORIXRHXI-BciDRWDC.js",
  "./assets/ocgcore.sync-ORIXRHXI-Ce1YOR3U.js",
  "./assets/ocgcore.sync-ORIXRHXI-CfWypg_V.js",
  "./assets/ocgcore.sync-ORIXRHXI-CluGo6mi.js",
  "./assets/ocgcore.sync-ORIXRHXI-CoPv54F1.js",
  "./assets/ocgcore.sync-ORIXRHXI-D0FWwmJG.js",
  "./assets/ocgcore.sync-ORIXRHXI-DfBPkZos.js",
  "./assets/ocgcore.sync-ORIXRHXI-FkzKzvjM.js",
  "./manifest.webmanifest",
  "./sprites/Fondo.png",
  "./sprites/Fondos (1).png",
  "./sprites/Fondos (2).png",
  "./sprites/Fondos (3).png",
  "./sprites/Fondos (4).png",
  "./sprites/Fondos (5).png",
  "./sprites/Menu-Fondo-Arena.png",
  "./sprites/Menu-Fondo-Noche.png",
  "./sprites/Menu-Fondo-Patio.png",
  "./sprites/Menu-Fondo-Santuario.png",
  "./sprites/Menu-Fondo-Templo.png",
  "./sprites/Sprite_Baldosa.png",
  "./sprites/Sprite_Baldosa2.png",
  "./sprites/Sprite_Baldosa3.png",
  "./sprites/Sprite_Canva-Carta.png",
  "./sprites/Sprite_Circular.png",
  "./sprites/Sprite_Escaleras.png",
  "./sprites/Sprite_Estandarte.png",
  "./sprites/Sprite_Estandarte2.png",
  "./sprites/Sprite_Flecha.png",
  "./sprites/Sprite_Hud.png",
  "./sprites/Sprite_Hud10.png",
  "./sprites/Sprite_Hud11.png",
  "./sprites/Sprite_Hud12.png",
  "./sprites/Sprite_Hud13.png",
  "./sprites/Sprite_Hud9.png",
  "./sprites/Sprite_Menu.png",
  "./sprites/Sprite_Menu2.png",
  "./sprites/Sprite_Menu3.png",
  "./sprites/Sprite_Menu4.png",
  "./sprites/Sprite_Menu5.png",
  "./sprites/Sprite_Menu6.png",
  "./sprites/Sprite_Menu7.png",
  "./sprites/Sprite_Menu8.png",
  "./sprites/Sprite_Ornamentacion.png",
  "./sprites/Sprite_Ornamentacion10.png",
  "./sprites/Sprite_Ornamentacion11.png",
  "./sprites/Sprite_Ornamentacion2.png",
  "./sprites/Sprite_Ornamentacion3.png",
  "./sprites/Sprite_ornamentacion4.png",
  "./sprites/Sprite_Ornamentacion5.png",
  "./sprites/Sprite_Ornamentacion6.png",
  "./sprites/Sprite_Ornamentacion7.png",
  "./sprites/Sprite_Ornamentacion8.png",
  "./sprites/Sprite_Ornamentacion9.png",
  "./sprites/Sprite_Ornamentacion_Esquina.png",
  "./sprites/Sprite_Pilar.png",
  "./sprites/Sprite_Submenu1.png",
  "./sprites/Sprite_Submenu10.png",
  "./sprites/Sprite_Submenu11.png",
  "./sprites/Sprite_Submenu12.png",
  "./sprites/Sprite_Submenu13.png",
  "./sprites/Sprite_Submenu2.png",
  "./sprites/Sprite_Submenu3.png",
  "./sprites/Sprite_Submenu4.png",
  "./sprites/Sprite_Submenu5.png",
  "./sprites/Sprite_Submenu6.png",
  "./sprites/Sprite_Submenu7.png",
  "./sprites/Sprite_Submenu8.png",
  "./sprites/Sprite_Submenu9.png",
  "./sprites/Tablero.png",
  "./sprites/Textura-Jeroglificos.png",
  "./sprites/Textura-Losa-Oscura.png",
  "./sprites/Textura-Mural.png",
  "./sprites/Texturas (1).png",
  "./sprites/Texturas (2).png",
  "./sprites/Texturas (3).png"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(async (cache) => {
      console.log("[PWA SW] Pre-caching all app assets for 100% offline play...");
      await Promise.allSettled(
        PRECACHE_ASSETS.map(async (url) => {
          try {
            const res = await fetch(url);
            if (res.ok || res.type === "opaque") {
              await cache.put(url, res);
            }
          } catch (e) {
            console.warn("[PWA SW] Non-fatal precache item skip:", url);
          }
        })
      );
      console.log("[PWA SW] Pre-cache complete! App is ready for offline play.");
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      );
    }).then(() => {
      console.log("[PWA SW] Claiming clients for offline control");
      return self.clients.claim();
    })
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  // 1. Navigation requests (opening the app from Home Screen / Safari offline)
  if (request.mode === "navigate" || request.destination === "document") {
    event.respondWith(
      (async () => {
        try {
          const networkResponse = await fetch(request);
          if (networkResponse && networkResponse.status === 200) {
            const cache = await caches.open(CACHE_NAME);
            cache.put(request, networkResponse.clone());
            return networkResponse;
          }
        } catch (e) {
          // Device is offline: retrieve index.html from cache
        }
        const cache = await caches.open(CACHE_NAME);
        const cached =
          (await cache.match(request)) ||
          (await cache.match("./index.html")) ||
          (await cache.match("index.html")) ||
          (await cache.match("./")) ||
          (await cache.match("/"));
        if (cached) return cached;
        return new Response("<!doctype html><html><body><h1>GOAT Lab Offline</h1></body></html>", {
          headers: { "Content-Type": "text/html" }
        });
      })()
    );
    return;
  }

  // 2. Static assets (JS, CSS, wasm, images, sprites, webmanifest)
  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      const cachedResponse = await cache.match(request, { ignoreSearch: true });
      if (cachedResponse) return cachedResponse;

      // Try matching by relative URL or pathname
      try {
        const url = new URL(request.url);
        const pathMatch = await cache.match("." + url.pathname, { ignoreSearch: true }) ||
                          await cache.match(url.pathname, { ignoreSearch: true });
        if (pathMatch) return pathMatch;
      } catch (_) {}

      try {
        const networkResponse = await fetch(request);
        if (networkResponse && (networkResponse.status === 200 || networkResponse.type === "opaque")) {
          const clone = networkResponse.clone();
          await cache.put(request, clone);
        }
        return networkResponse;
      } catch (err) {
        // Fallback search in cache by filename
        try {
          const url = new URL(request.url);
          const filename = url.pathname.split("/").pop();
          if (filename) {
            const match = await cache.match(filename, { ignoreSearch: true }) ||
                          await cache.match("./sprites/" + filename, { ignoreSearch: true }) ||
                          await cache.match("./assets/" + filename, { ignoreSearch: true });
            if (match) return match;
          }
        } catch (_) {}

        // For images, return a dummy 1x1 transparent PNG fallback instead of throwing
        if (request.destination === "image") {
          return new Response(
            new Uint8Array([
              0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d,
              0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
              0x08, 0x06, 0x00, 0x00, 0x00, 0x1f, 0x15, 0xc4, 0x89, 0x00, 0x00, 0x00,
              0x0a, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9c, 0x63, 0x00, 0x01, 0x00, 0x00,
              0x05, 0x00, 0x01, 0x0d, 0x0a, 0x2d, 0xb4, 0x00, 0x00, 0x00, 0x00, 0x49,
              0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82
            ]),
            { headers: { "Content-Type": "image/png" } }
          );
        }
        return new Response("", { status: 404, statusText: "Offline Resource Unavailable" });
      }
    })()
  );
});
