// Autogenerated offline Service Worker for GOAT Local Lab
const CACHE_NAME = "goat-ipad-offline-v1787213052640";

const PRECACHE_ASSETS = [
  "./",
  "./index.html",
  "index.html",
  "./assets/card-audit-Beewvp04.js",
  "./assets/card-audit-scenario-CnX-wbYE.js",
  "./assets/card-viewer-DS9QH6M9.js",
  "./assets/chunk-6GYI7QPM-C3jnHFg4.js",
  "./assets/main-DC4uBPQ3.css",
  "./assets/main-DSneyimg.js",
  "./assets/manifest-CblUBTob.webmanifest",
  "./assets/ocgcore-script-sources-D13qckf3.js",
  "./assets/ocgcore.jspi-ROQIC75H-tARKdj7h.js",
  "./assets/ocgcore.jspi-W7UMOWZG-jNzO_Kkj.js",
  "./assets/ocgcore.sync-MMMSWPBB-DC7TXYad.js",
  "./assets/ocgcore.sync-ORIXRHXI-CPJYFi70.js",
  "./manifest.webmanifest",
  "./sprites/Fondo.png",
  "./sprites/Fondos (1).png",
  "./sprites/Fondos (2).png",
  "./sprites/Fondos (3).png",
  "./sprites/Fondos (4).png",
  "./sprites/Fondos (5).png",
  "./sprites/Menu-Fondo-Arena.png",
  "./sprites/Menu-Fondo-Noche.png",
  "./sprites/Menu-Fondo-Patio.png",
  "./sprites/Menu-Fondo-Santuario.png",
  "./sprites/Menu-Fondo-Templo.png",
  "./sprites/Sprite_Baldosa.png",
  "./sprites/Sprite_Baldosa2.png",
  "./sprites/Sprite_Baldosa3.png",
  "./sprites/Sprite_Canva-Carta.png",
  "./sprites/Sprite_Circular.png",
  "./sprites/Sprite_Escaleras.png",
  "./sprites/Sprite_Estandarte.png",
  "./sprites/Sprite_Estandarte2.png",
  "./sprites/Sprite_Flecha.png",
  "./sprites/Sprite_Hud.png",
  "./sprites/Sprite_Hud10.png",
  "./sprites/Sprite_Hud11.png",
  "./sprites/Sprite_Hud12.png",
  "./sprites/Sprite_Hud13.png",
  "./sprites/Sprite_Hud9.png",
  "./sprites/Sprite_Menu.png",
  "./sprites/Sprite_Menu2.png",
  "./sprites/Sprite_Menu3.png",
  "./sprites/Sprite_Menu4.png",
  "./sprites/Sprite_Menu5.png",
  "./sprites/Sprite_Menu6.png",
  "./sprites/Sprite_Menu7.png",
  "./sprites/Sprite_Menu8.png",
  "./sprites/Sprite_Ornamentacion.png",
  "./sprites/Sprite_Ornamentacion10.png",
  "./sprites/Sprite_Ornamentacion11.png",
  "./sprites/Sprite_Ornamentacion2.png",
  "./sprites/Sprite_Ornamentacion3.png",
  "./sprites/Sprite_ornamentacion4.png",
  "./sprites/Sprite_Ornamentacion5.png",
  "./sprites/Sprite_Ornamentacion8.png",
  "./sprites/Sprite_Ornamentacion9.png",
  "./sprites/Sprite_Ornamentacion_Esquina.png",
  "./sprites/Sprite_Ornamentación6.png",
  "./sprites/Sprite_Ornamentación7.png",
  "./sprites/Sprite_Pilar.png",
  "./sprites/Sprite_Submenu1.png",
  "./sprites/Sprite_Submenu10.png",
  "./sprites/Sprite_Submenu11.png",
  "./sprites/Sprite_Submenu12.png",
  "./sprites/Sprite_Submenu13.png",
  "./sprites/Sprite_Submenu2.png",
  "./sprites/Sprite_Submenu3.png",
  "./sprites/Sprite_Submenu4.png",
  "./sprites/Sprite_Submenu5.png",
  "./sprites/Sprite_Submenu6.png",
  "./sprites/Sprite_Submenu7.png",
  "./sprites/Sprite_Submenu8.png",
  "./sprites/Sprite_Submenu9.png",
  "./sprites/Tablero.png",
  "./sprites/Textura-Jeroglificos.png",
  "./sprites/Textura-Losa-Oscura.png",
  "./sprites/Textura-Mural.png",
  "./sprites/Texturas (1).png",
  "./sprites/Texturas (2).png",
  "./sprites/Texturas (3).png"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(async (cache) => {
      console.log("[PWA SW] Pre-caching all app assets for 100% offline play...");
      await Promise.allSettled(
        PRECACHE_ASSETS.map(async (url) => {
          try {
            const res = await fetch(url);
            if (res.ok || res.type === "opaque") {
              await cache.put(url, res);
            }
          } catch (e) {
            console.warn("[PWA SW] Non-fatal precache item skip:", url);
          }
        })
      );
      console.log("[PWA SW] Pre-cache complete! App is ready for offline play.");
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      );
    }).then(() => {
      console.log("[PWA SW] Claiming clients for offline control");
      return self.clients.claim();
    })
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  // 1. Navigation requests (opening the app from Home Screen / Safari offline)
  if (request.mode === "navigate" || request.destination === "document") {
    event.respondWith(
      (async () => {
        try {
          const networkResponse = await fetch(request);
          if (networkResponse && networkResponse.status === 200) {
            const cache = await caches.open(CACHE_NAME);
            cache.put(request, networkResponse.clone());
            return networkResponse;
          }
        } catch (e) {
          // Device is offline: retrieve index.html from cache
        }
        const cache = await caches.open(CACHE_NAME);
        const cached =
          (await cache.match(request)) ||
          (await cache.match("./index.html")) ||
          (await cache.match("index.html")) ||
          (await cache.match("./")) ||
          (await cache.match("/"));
        if (cached) return cached;
        return new Response("<!doctype html><html><body><h1>GOAT Lab Offline</h1></body></html>", {
          headers: { "Content-Type": "text/html" }
        });
      })()
    );
    return;
  }

  // 2. Static assets (JS, CSS, wasm, images, sprites, webmanifest)
  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then(async (cachedResponse) => {
      if (cachedResponse) {
        return cachedResponse;
      }
      try {
        const networkResponse = await fetch(request);
        if (networkResponse && (networkResponse.status === 200 || networkResponse.type === "opaque")) {
          const clone = networkResponse.clone();
          const cache = await caches.open(CACHE_NAME);
          await cache.put(request, clone);
        }
        return networkResponse;
      } catch (err) {
        // Fallback search in cache by relative path
        try {
          const cache = await caches.open(CACHE_NAME);
          const url = new URL(request.url);
          const filename = url.pathname.split("/").pop();
          if (filename) {
            const match = await cache.match(filename, { ignoreSearch: true });
            if (match) return match;
          }
        } catch (_) {}

        // For images, return a dummy 1x1 transparent PNG fallback instead of throwing
        if (request.destination === "image") {
          return new Response(
            new Uint8Array([
              0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d,
              0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
              0x08, 0x06, 0x00, 0x00, 0x00, 0x1f, 0x15, 0xc4, 0x89, 0x00, 0x00, 0x00,
              0x0a, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9c, 0x63, 0x00, 0x01, 0x00, 0x00,
              0x05, 0x00, 0x01, 0x0d, 0x0a, 0x2d, 0xb4, 0x00, 0x00, 0x00, 0x00, 0x49,
              0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82
            ]),
            { headers: { "Content-Type": "image/png" } }
          );
        }
        return new Response("", { status: 404, statusText: "Offline Resource Unavailable" });
      }
    })
  );
});
