// Autogenerated offline Service Worker for GOAT Local Lab
const CACHE_NAME = "goat-ipad-offline-v1789224515165";

const PRECACHE_ASSETS = [
  "./",
  "./index.html",
  "index.html",
  "./assets/card-audit-D0Wms7G_.js",
  "./assets/card-audit-scenario-BYqbHLsE.js",
  "./assets/card-viewer-BsriykxS.js",
  "./assets/chunk-6GYI7QPM-C3jnHFg4.js",
  "./assets/main-Cuj98LW0.css",
  "./assets/main-D23FsuVe.js",
  "./assets/manifest-CblUBTob.webmanifest",
  "./assets/ocgcore-script-sources-DR41tm-N.js",
  "./assets/ocgcore.jspi-ROQIC75H-BGTpk2tL.js",
  "./assets/ocgcore.jspi-W7UMOWZG-DN_kbRwi.js",
  "./assets/ocgcore.sync-MMMSWPBB-Ea7G4N59.js",
  "./assets/ocgcore.sync-ORIXRHXI-NzpHRZLe.js",
  "./manifest.webmanifest",
  "./sprites/Arquero.webp",
  "./sprites/Arquero_Diamante.webp",
  "./sprites/Bronce.webp",
  "./sprites/Diamante.webp",
  "./sprites/EnemyLord.webp",
  "./sprites/Esmeralda.webp",
  "./sprites/Esperalda.webp",
  "./sprites/Fondo.webp",
  "./sprites/Fondos (1).webp",
  "./sprites/Fondos (2).webp",
  "./sprites/Fondos (3).webp",
  "./sprites/Fondos (4).webp",
  "./sprites/Fondos (5).webp",
  "./sprites/Guerrero.webp",
  "./sprites/Guerrero_Diamante.webp",
  "./sprites/Menu-Fondo-Arena.webp",
  "./sprites/Menu-Fondo-Noche.webp",
  "./sprites/Menu-Fondo-Patio.webp",
  "./sprites/Menu-Fondo-Santuario.webp",
  "./sprites/Menu-Fondo-Templo.webp",
  "./sprites/Monje.webp",
  "./sprites/Monje_Diamante.webp",
  "./sprites/Oro.webp",
  "./sprites/Sacerdotisa.webp",
  "./sprites/Sacerdotisa_Diamante.webp",
  "./sprites/Sprite_Baldosa.webp",
  "./sprites/Sprite_Baldosa2.webp",
  "./sprites/Sprite_Baldosa3.webp",
  "./sprites/Sprite_Canva-Carta.webp",
  "./sprites/Sprite_Circular.webp",
  "./sprites/Sprite_Escaleras.webp",
  "./sprites/Sprite_Estandarte.webp",
  "./sprites/Sprite_Estandarte2.webp",
  "./sprites/Sprite_Flecha.webp",
  "./sprites/Sprite_Hud.webp",
  "./sprites/Sprite_Hud10.webp",
  "./sprites/Sprite_Hud11.webp",
  "./sprites/Sprite_Hud12.webp",
  "./sprites/Sprite_Hud13.webp",
  "./sprites/Sprite_Hud9.webp",
  "./sprites/Sprite_Menu.webp",
  "./sprites/Sprite_Menu2.webp",
  "./sprites/Sprite_Menu3.webp",
  "./sprites/Sprite_Menu4.webp",
  "./sprites/Sprite_Menu5.webp",
  "./sprites/Sprite_Menu6.webp",
  "./sprites/Sprite_Menu7.webp",
  "./sprites/Sprite_Menu8.webp",
  "./sprites/Sprite_Ornamentacion.webp",
  "./sprites/Sprite_Ornamentacion10.webp",
  "./sprites/Sprite_Ornamentacion11.webp",
  "./sprites/Sprite_Ornamentacion2.webp",
  "./sprites/Sprite_Ornamentacion3.webp",
  "./sprites/Sprite_ornamentacion4.webp",
  "./sprites/Sprite_Ornamentacion5.webp",
  "./sprites/Sprite_Ornamentacion6.webp",
  "./sprites/Sprite_Ornamentacion7.webp",
  "./sprites/Sprite_Ornamentacion8.webp",
  "./sprites/Sprite_Ornamentacion9.webp",
  "./sprites/Sprite_Ornamentacion_Esquina.webp",
  "./sprites/Sprite_Ornamentación6.webp",
  "./sprites/Sprite_Ornamentación7.webp",
  "./sprites/Sprite_Pilar.webp",
  "./sprites/Sprite_Submenu1.webp",
  "./sprites/Sprite_Submenu10.webp",
  "./sprites/Sprite_Submenu11.webp",
  "./sprites/Sprite_Submenu12.webp",
  "./sprites/Sprite_Submenu13.webp",
  "./sprites/Sprite_Submenu2.webp",
  "./sprites/Sprite_Submenu3.webp",
  "./sprites/Sprite_Submenu4.webp",
  "./sprites/Sprite_Submenu5.webp",
  "./sprites/Sprite_Submenu6.webp",
  "./sprites/Sprite_Submenu7.webp",
  "./sprites/Sprite_Submenu8.webp",
  "./sprites/Sprite_Submenu9.webp",
  "./sprites/Tablero.webp",
  "./sprites/Textura-Jeroglificos.webp",
  "./sprites/Textura-Losa-Oscura.webp",
  "./sprites/Textura-Mural.webp",
  "./sprites/Texturas (1).webp",
  "./sprites/Texturas (2).webp",
  "./sprites/Texturas (3).webp",
  "./sprites/Unranked.webp"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(async (cache) => {
      console.log("[PWA SW] Pre-caching all app assets for 100% offline play...");
      await Promise.allSettled(
        PRECACHE_ASSETS.map(async (url) => {
          try {
            const res = await fetch(url);
            if (res.ok || res.type === "opaque") {
              await cache.put(url, res);
            }
          } catch (e) {
            console.warn("[PWA SW] Non-fatal precache item skip:", url);
          }
        })
      );
      console.log("[PWA SW] Pre-cache complete! App is ready for offline play.");
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      );
    }).then(() => {
      console.log("[PWA SW] Claiming clients for offline control");
      return self.clients.claim();
    })
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  // 1. Navigation requests (opening the app from Home Screen / Safari offline)
  if (request.mode === "navigate" || request.destination === "document") {
    event.respondWith(
      (async () => {
        try {
          const networkResponse = await fetch(request);
          if (networkResponse && networkResponse.status === 200) {
            const cache = await caches.open(CACHE_NAME);
            cache.put(request, networkResponse.clone());
            return networkResponse;
          }
        } catch (e) {
          // Device is offline: retrieve index.html from cache
        }
        const cache = await caches.open(CACHE_NAME);
        const cached =
          (await cache.match(request)) ||
          (await cache.match("./index.html")) ||
          (await cache.match("index.html")) ||
          (await cache.match("./")) ||
          (await cache.match("/"));
        if (cached) return cached;
        return new Response("<!doctype html><html><body><h1>GOAT Lab Offline</h1></body></html>", {
          headers: { "Content-Type": "text/html" }
        });
      })()
    );
    return;
  }

  // 2. Static assets (JS, CSS, wasm, images, sprites, webmanifest)
  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      const cachedResponse = await cache.match(request, { ignoreSearch: true });
      if (cachedResponse) return cachedResponse;

      // Try matching by relative URL or pathname
      try {
        const url = new URL(request.url);
        const pathMatch = await cache.match("." + url.pathname, { ignoreSearch: true }) ||
                          await cache.match(url.pathname, { ignoreSearch: true });
        if (pathMatch) return pathMatch;
      } catch (_) {}

      try {
        const networkResponse = await fetch(request);
        if (networkResponse && (networkResponse.status === 200 || networkResponse.type === "opaque")) {
          const clone = networkResponse.clone();
          await cache.put(request, clone);
        }
        return networkResponse;
      } catch (err) {
        // Fallback search in cache by filename
        try {
          const url = new URL(request.url);
          const filename = url.pathname.split("/").pop();
          if (filename) {
            const match = await cache.match(filename, { ignoreSearch: true }) ||
                          await cache.match("./sprites/" + filename, { ignoreSearch: true }) ||
                          await cache.match("./assets/" + filename, { ignoreSearch: true });
            if (match) return match;
          }
        } catch (_) {}

        // For images, return a dummy 1x1 transparent PNG fallback instead of throwing
        if (request.destination === "image") {
          return new Response(
            new Uint8Array([
              0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d,
              0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
              0x08, 0x06, 0x00, 0x00, 0x00, 0x1f, 0x15, 0xc4, 0x89, 0x00, 0x00, 0x00,
              0x0a, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9c, 0x63, 0x00, 0x01, 0x00, 0x00,
              0x05, 0x00, 0x01, 0x0d, 0x0a, 0x2d, 0xb4, 0x00, 0x00, 0x00, 0x00, 0x49,
              0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82
            ]),
            { headers: { "Content-Type": "image/png" } }
          );
        }
        return new Response("", { status: 404, statusText: "Offline Resource Unavailable" });
      }
    })()
  );
});
