import { GOAT_CARD_POOL_SOURCE } from "../data/goat-card-pool.js";

export const ENGINE_VERSION = "engine-0.1.0-vertical";
export const FORMAT_VERSION = "goat-tcg-apr-2005-v0.1";
export const CARD_DATABASE_VERSION = `goatformat-cardpool-${GOAT_CARD_POOL_SOURCE.sourceSha256.slice(0, 8)}`;

export const PHASE = Object.freeze({
  DRAW: "DRAW",
  STANDBY: "STANDBY",
  MAIN_1: "MAIN_1",
  BATTLE: "BATTLE",
  MAIN_2: "MAIN_2",
  END: "END"
});

export const CARD_KIND = Object.freeze({
  MONSTER: "MONSTER",
  SPELL: "SPELL",
  TRAP: "TRAP",
  TOKEN: "TOKEN"
});

export const MONSTER_POSITION = Object.freeze({
  ATTACK: "ATTACK",
  DEFENSE: "DEFENSE"
});

export const ZONE = Object.freeze({
  DECK: "DECK",
  HAND: "HAND",
  MONSTER: "MONSTER",
  SPELL_TRAP: "SPELL_TRAP",
  GRAVE: "GRAVE",
  BANISHED: "BANISHED",
  FUSION: "FUSION"
});

export const ACTION = Object.freeze({
  ADVANCE_PHASE: "ADVANCE_PHASE",
  SUMMON: "SUMMON",
  SET_MONSTER: "SET_MONSTER",
  SET_SPELL_TRAP: "SET_SPELL_TRAP",
  ACTIVATE_MONSTER: "ACTIVATE_MONSTER",
  ACTIVATE_SPELL: "ACTIVATE_SPELL",
  ACTIVATE_TRAP: "ACTIVATE_TRAP",
  ATTACK: "ATTACK",
  CHANGE_POSITION: "CHANGE_POSITION",
  PASS_PRIORITY: "PASS_PRIORITY",
  SURRENDER: "SURRENDER"
});

export const TERMINATION = Object.freeze({
  LIFE_POINTS: "LIFE_POINTS",
  DECK_OUT: "DECK_OUT",
  SURRENDER: "SURRENDER",
  DECISION_LIMIT: "DECISION_LIMIT",
  TURN_LIMIT: "TURN_LIMIT",
  INVALID_ACTION: "INVALID_ACTION"
});

export const VALIDATION_STATUS = Object.freeze({
  SUPPORTED: "SUPPORTED",
  PARTIAL: "PARTIAL",
  EXPERIMENTAL: "EXPERIMENTAL",
  REQUIRES_VALIDATION: "REQUIRES_VALIDATION",
  REQUIRES_RULING_REVIEW: "REQUIRES_RULING_REVIEW",
  BLOCKED_BY_MISSING_SOURCE: "BLOCKED_BY_MISSING_SOURCE",
  FAILED_REGRESSION: "FAILED_REGRESSION",
  UNSUPPORTED: "UNSUPPORTED"
});

export const MAX_MONSTERS = 5;
export const MAX_SPELL_TRAPS = 5;
export const STARTING_LIFE_POINTS = 8000;
export const STARTING_HAND_SIZE = 5;
export const MAX_DECISIONS = 500;
export const MAX_TURNS = 80;
